Reworked some error messages

diff --git a/support/dev b/support/dev
--- a/support/dev
+++ b/support/dev
@@ -69,7 +69,7 @@ function parse_args # [args ...]
 #    exit 1
 #  fi
 
-  [ $# -lt 1 ] && >&2 echo "Missing argument <action>." && exit 1
+  [ $# -lt 1 ] && >&2 echo "Missing command arguments. Check usage using '-h'." && exit 1
   CMD_ACTION=$1
   shift
 
@@ -101,11 +101,9 @@ function parse_args # [args ...]
         ;;
     esac
   done
-
   shift $((OPTIND -1))
-  [ $# -lt 1 ] && >&2 echo "Missing argument <image>." && exit 1
-  CMD_DOCKER_IMAGE="$1"
-  shift
+
+  [ $# -ne 0 ] || CMD_DOCKER_IMAGE="$1" && shift
 
   # Make sure all remaining args are passed to docker as command
   if [ $# -ne 0 ] ; then
@@ -147,8 +145,8 @@ function find_image_id() {
 }
 
 function find_image_name() {
-    local docker_image=$1
-    local working_dir=$2
+    local docker_image=${1:?Missing docker image.}
+    local working_dir=${2:?Missing working directory.}
     local image_name=$(docker ps -q | xargs --no-run-if-empty docker inspect --format "{{ if eq .Config.Image \"${docker_image}\" }}{{ range .Mounts }}{{ if eq .Source \"${working_dir}\" }}{{ $.Name }}{{ end }}{{ end }}{{ end }}")
     image_name=${image_name:1}
 
@@ -158,7 +156,7 @@ function find_image_name() {
 }
 
 function docker_run() {
-  local image_name="$(find_image_name ${CMD_DOCKER_IMAGE} ${CMD_WORKING_DIR})"
+  local image_name="$(find_image_name "${CMD_DOCKER_IMAGE}" "${CMD_WORKING_DIR}")"
 
   [[ -n $image_name ]] && >&2 printf "Container '$image_name' for image '${CMD_DOCKER_IMAGE}' already running in working directory '${CMD_WORKING_DIR}'.\nUse command '$0 exec ${CMD_DOCKER_IMAGE} ${CMD_WORKING_DIR}' to enter running container.\n" && exit 1
 
@@ -175,7 +173,7 @@ function docker_run() {
 }
 
 function docker_exec() {
-  local image_name="$(find_image_name ${CMD_DOCKER_IMAGE} ${CMD_WORKING_DIR})"
+  local image_name="$(find_image_name "${CMD_DOCKER_IMAGE}" "${CMD_WORKING_DIR}")"
 
   if [[ -z "$image_name" ]]; then
     >&2 echo "No container found for image '${CMD_DOCKER_IMAGE}' running in working directory '${CMD_WORKING_DIR}'."
@@ -186,7 +184,7 @@ function docker_exec() {
 }
 
 function docker_ps() {
-  local image_name="$(find_image_name ${CMD_DOCKER_IMAGE} ${CMD_WORKING_DIR})"
+  local image_name="$(find_image_name "${CMD_DOCKER_IMAGE}" "${CMD_WORKING_DIR}")"
 
   if [[ -z "$image_name" ]]; then
     >&2 echo "No container found for image '${CMD_DOCKER_IMAGE}' running in working directory '${CMD_WORKING_DIR}'."
